site_name: Mizar Project
docs_dir: 'docs'
site_dir: '.tmp/documentation'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - Home: 'index.md'
    - 'Getting Started':
        - Basic Usage: 'user/getting_started.md'
        - Developement: 'dev/contributing.md'
    - 'Data Plane Design':
        - 'Data-Plane Overview': 'design/data_plane.md'
        - 'Tunneling Protocols': 'design/tunneling_protocols.md'
        - 'Data-Plane Data Model': 'design/dp_datamodel.md'
        - 'Data-Plane Extensibility': 'design/extensibility.md'
        - 'Direct Path': 'design/direct_path.md'
        - 'Scaled Endpoint': 'design/scaled_endpoint.md'
    - 'Management Plane Design':
        - 'Management-Plane Overview': 'design/management_plane.md'
    - About:
        #- 'License': 'license.md'
        - 'Use Cases': 'releases/use_cases.md'
        - 'Release Notes': 'releases/release-notes.md'
        - 'Roadmap' : 'releases/roadmap.md'
    - 'Frequently Asked Questions': 'user/faq.md'