apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-init
  namespace: default
spec:
  selector:
    matchLabels:
      job: node-init
  template:
    metadata:
      labels:
        job: node-init
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: fwnetworking/mizar:node-init
        name: node-init
        securityContext:
          privileged: true