apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: transitd
  namespace: default
spec:
  selector:
    matchLabels:
      job: transitd
  template:
    metadata:
      labels:
        job: transitd
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: fwnetworking/mizar:mizar-setup
        name: transitd
        command: ["./transitd-start.sh"]
        securityContext:
          privileged: true
